sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
sudo ./demo_mb_ls -f ec_up_pcm -m E006.fd -c 1;sleep 5;sudo reboot 
